booking:
  color: "#99bbf2"
  items:
    booking-api:
      backends:
      - inventory-api
      - user-management-api
    availability-api:
      backends:
      - booking-api
      - user-management-api
vehicles:
  color: "#dab1e0"
  items:
    inventory-api: {}
payment:
  color: "#b1e0c9"
  items:
    payment-gateway-api: {}
users:
  color: "#dce0b1"
  items:
    user-management-api: {}
